export default function Head() {
	return (
		<>
			<title>Tower of Hanoi</title>
			<meta charSet='UTF-8' />
			<meta content='width=device-width, initial-scale=1' name='viewport' />
			<meta name='description' content='Generated by create next app' />
			<link rel='icon' href='/icon.png' />
		</>
	);
}
